# Generated by Django 3.2.16 on 2023-06-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
